version: '3'

services:
  mongodb-primary:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    # volumes:
    #   - ./data:/data/db
  mongodb-secondary:
    image: mongo
    restart: always
    ports:
      - '27018:27018'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    # volumes:
    #   - ./data:/data/db
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
